# NumPy

In [26]:
import numpy as np #import numpy module

#Using numpy to calculate the BMI for elements stored in a list

height = [4,5,6,7,7]
weight = [2,9,9,9.1,8]

np_height = np.array(height)
np_weight = np.array(weight)
np_weight/np_height ** 2

#If the elements are of different types like string and float, everything gets converted to string
#Be careful of using list operands on numpy arrays - they function differently. Ex: "+" is an addition of arrays 


array([0.125     , 0.36      , 0.25      , 0.18571429, 0.16326531])

In [27]:
#creating an array
a = np.array([[1,2,3],[4,5,'String']])
a.dtype #to check a data type of an array. U11 is string

#use 'a.shape' to show the dimensions of the array, 'a.size' will give total elements in array
#'a.itemsize' will give size of the element like 8 bytes etc. 

dtype('<U11')

In [35]:
#creating arrays 
ones = np.ones((3,4), dtype = int) #create arrays with value 1. You can create value 0 using np.zeros
print(ones)


same_element = np.full((4,4),12) #creates 4x4 array with value 12
print(same_element)


#using arange to create ranges. 
print(np.arange(10,1,-1))

#using reshape to determine the shape of an array on above
print(np.arange(10,1,-1).reshape(3,3))


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[10  9  8  7  6  5  4  3  2]
[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]


In [50]:
#Using %timeit to get the execution time of statements

%timeit sum([a for a in range(9,999)]) #with regular for statement

24 µs ± 826 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [52]:
%timeit np.arange(9,999).sum() #with numpy array, the time taken to execute is less

2.5 µs ± 23.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [56]:
#when comparing two arrays with operands, the operand compares element in each array
#You can also use functions like 'ones.sum()' to get the sum of array elements. 
#You can also use min, max, mean, std

In [60]:
ratings = np.array([[87, 96, 70], [100, 87, 90],
    [94, 77, 90], [100, 81, 82]])
ratings.mean(axis=0) #axis 0 performs calculation on all row values within each column

array([95.25, 85.25, 83.  ])

In [68]:
#selecting a subset of arrays
print(ratings[0:2])

print(ratings[1:,0])

[[ 87  96  70]
 [100  87  90]]
[100  94 100]


In [70]:
#Transposing rows and columns
ratings.T

array([[ 87, 100,  94, 100],
       [ 96,  87,  77,  81],
       [ 70,  90,  90,  82]])

# Strings